experiment: exp9_1_basisExpert_ocean_xyzt_no_moe
exp_id: basisExpert-ocean-multiview-no-moe
experiment_root: experiments
data:
  dataset_name: ocean
  split: train
  data_root: ./data
  x_path: ./data/raw/ocean/train/source_XYZT_sub.npy
  attr_paths:
    data_fort63: ./data/raw/ocean/train/target_fort63_sub.npy
    data_fort64: ./data/raw/ocean/train/target_fort64_sub.npy
    data_fort73: ./data/raw/ocean/train/target_fort73_sub.npy
    data_V_time: ./data/raw/ocean/train/target_V_time_sub.npy
    data_Speed_time: ./data/raw/ocean/train/target_Speed_time_sub.npy
  normalize: true
model:
  name: baisiExpert_NoMoE
  in_features: 4
  num_experts: 1
  base_dim: 8
  expert_use_positional_encoding: true
  expert_num_frequencies: 6
  expert_num_layers: 2
  decoder_num_layers: 2
  expert_first_omega_0: 30.0
  expert_hidden_omega_0: 30.0
  decoder_first_omega_0: 30.0
  decoder_hidden_omega_0: 30.0
  fusion_num_layers: 2
  fusion_num_heads: 4
  fusion_mlp_ratio: 1.0
  fusion_dropout: 0.1
training:
  num_workers: 4
  epochs: 60
  batch_size: 8192
  pred_batch_size: 8192
  lr: 5.0e-05
  log_every: 1
  save_every: 10
  early_stop_patience: 0
  seed: 42
  loss_type: mse
  lam_eq: 0.0
  gam_div: 0.0
