experiment: exp9_basisExpert_sukong_multiview_xyzt_mlp
exp_id: basisExpert-sukong-multiview-mlp
experiment_root: experiments
data:
  dataset_name: sukong
  split: train
  data_root: ./data
  x_path: ./data/raw/sukong/train/source_cell_XYZT.npy
  attr_paths:
    target_E: ./data/raw/sukong/train/target_cell_E.npy
    target_E_IntegrationPoints: ./data/raw/sukong/train/target_cell_E_IntegrationPoints.npy
    target_S: ./data/raw/sukong/train/target_cell_S.npy
    target_S_IntegrationPoints: ./data/raw/sukong/train/target_cell_S_IntegrationPoints.npy
  normalize: true
model:
  name: basisExpert_simple_concat
  fusion_mode: mlp
  in_features: 4
  num_experts: 7
  base_dim: 4
  top_k: 2
  expert_use_positional_encoding: true
  expert_num_frequencies: 6
  expert_num_layers: 3
  gate_num_layers: 3
  decoder_num_layers: 3
  expert_first_omega_0: 30.0
  expert_hidden_omega_0: 30.0
  gate_first_omega_0: 30.0
  gate_hidden_omega_0: 30.0
  decoder_first_omega_0: 30.0
  decoder_hidden_omega_0: 30.0
  fusion_num_layers: 2
  fusion_num_heads: 4
  fusion_mlp_ratio: 4.0
  fusion_dropout: 0.1
training:
  num_workers: 4
  epochs: 60
  batch_size: 8192
  pred_batch_size: 8192
  lr: 5.0e-5
  log_every: 1
  save_every: 10
  early_stop_patience: 0
  seed: 42
  loss_type: mse
  lam_eq: 1.0e-2
  gam_div: 1.0e-3
