seed: 0
wandb_project: "inr_moe_mesh"

MODEL:
  model_name: "inr_moe_mesh"
  in_dim: 4
  out_dim: 24
  decoder_hidden_dim: 64
  decoder_n_hidden_layers: 2
  decoder_input_encoding: "learned_512_2_sine_siren_none"
  decoder_nl: "sine"
  decoder_init_type: "siren"
  n_experts: 8
  outermost_linear: True
  input_encoding: "none"
  decoder_freqs: 30.0
  decoder_trainable_freqs: False
  top_k: 1
  manager_hidden_dim: 128
  manager_n_hidden_layers: 2
  manager_input_encoding: "learned_128_2_sine_siren_none"
  manager_nl: "sine"
  manager_init: "siren"
  manager_type: "standard"
  experts_bias_std: 0.1
  experts_bias_weight: 1.0
  manager_softmax_temperature: 1.0
  manager_softmax_temp_trainable: False
  manager_q_activation: "softmax"
  manager_clamp_q: 0.0
  manager_conditioning: "cat"
  manager_pt_path: "../../pretrained_managers/stress/pt_inr_moe_mesh_stress_cell_E_managerpretraining.pth"
  load_pt_manager: True
  shared_encoder: False

LOSS:
  scale_by_q_grad: False
  loss_type: "1000valrecon"
  segmentation_type: "ce"
  sample_bias_correction: False
  entropy_metric: "kl"

DATA:
  dataset_name: "stress"
  attr_name: "cell_E"
  association: "cell"
  source_path: "../../../data/raw/stress/train/source_cell_XYZT.npy"
  target_path: "../../../data/raw/stress/train/target_cell_E.npy"
  target_stats_path: "../../../data/raw/stress/train/target_stats_multi.npz"
  stats_key: "target_E"
  normalize_inputs: True
  normalize_targets: True

TRAINING:
  n_points: 10000
  lr: 3.0e-5
  lr_gamma: 0.9999
  lr_scheduler: "ExponentialLR"
  num_epochs: 30000
  batch_size: 1
  num_workers: 0
  grad_clip_norm: 10.0
  save_every: 500
  segmentation_mode: False
  pretrain_assignment:
    method: "coord_kmeans"
    fit_samples: 50000
    cache_path: "../../../data/cache/neural_experts_stress_cell_E_coord_kmeans.npz"
    normalize_features: True
    random_seed: 0
    chunk_size: 65536
  stages: [
           {"end_iteration_frac": 1.0, "params":"all", "loss_type": "1000valrecon" }
          ]
