seed: 0
wandb_project: 'inr_moe_ionization'

MODEL:
  model_name: 'inr_moe_ionization'
  in_dim: 4
  out_dim: 1
  decoder_hidden_dim: 64
  decoder_n_hidden_layers: 2
  decoder_input_encoding: 'learned_512_2_sine_siren_none'
  decoder_nl: 'sine'
  decoder_init_type: 'siren'
  n_experts: 8
  outermost_linear: True
  input_encoding: 'none'
  decoder_freqs: 30.
  decoder_trainable_freqs: False
  top_k: 1

  manager_hidden_dim: 128
  manager_n_hidden_layers: 2
  manager_input_encoding: 'learned_128_2_sine_siren_none'
  manager_nl: 'sine'
  manager_init: 'siren'
  manager_type: 'standard'
  experts_bias_std: 0.1
  experts_bias_weight: 1.0
  manager_softmax_temperature: 1.0
  manager_softmax_temp_trainable: False
  manager_q_activation: 'softmax'
  manager_clamp_q: 0.0
  manager_conditioning: 'cat'
  manager_pt_path: '../../pretrained_managers/ionization/pt_inr_moe_ionization_Hplus_managerpretraining.pth'
  load_pt_manager: False
  shared_encoder: False

LOSS:
  scale_by_q_grad: False
  loss_type: '1000segmentation'
  segmentation_type: 'ce'
  sample_bias_correction: False
  entropy_metric: 'kl'

DATA:
  target_path: '../../../data/raw/ionization/train/target_H+.npy'
  target_stats_path: '../../../data/raw/ionization/train/target_stats_H+.npz'
  attr_name: 'H+'
  name: 'ionization'
  volume_shape:
    X: 600
    Y: 248
    Z: 248
    T: 100
  normalize_inputs: True
  normalize_targets: False
  segmentation_type: 'random_balanced'
  grid_patch_size: 4
  n_segments: 8

TRAINING:
  n_points: 10000
  nonmnfld_sample_type: 'combined'
  grid_res: 128
  grid_eval_res: 512
  grid_range: 1.2
  lr: 3.0e-5
  lr_gamma: 0.9999
  lr_scheduler: 'ExponentialLR'
  num_epochs: 30000
  batch_size: 1
  num_workers: 0
  refine_epoch: 0
  grad_clip_norm: 10.0
  export_vis: False
  manager_freeze_fraction: 0.15
  segmentation_mode: True
  stages: [
           {'end_iteration_frac': 1.0, 'params':'all', 'loss_type': '1000segmentation' }
          ]
