input: ../path/to/volRendering_H2.npy
zfp: build/bin/zfp
psnr: 40.0
# tolerance: 0.01  # Use exactly one of psnr, tolerance, or rate.
# rate: 8.0        # Bits per value.
shape: [600, 248, 248]

compressed: outputs/volRendering_H2.zfp
recon: outputs/volRendering_H2_recon.npy
result_json: outputs/volRendering_H2_result.json
