experiment: exp_coordnet_e_time
exp_id: coordnet-centroids-e_time
experiment_root: experiments
data:
  dataset_name: centroids
  split: train
  data_root: ./data
  x_path: ./data/raw/centroids/train/coords_xyzt.npy
  y_path: ./data/raw/centroids/train/targets_e_time.npy
  normalize: true
model:
  name: coordnet
  in_features: 4
  out_features: 24
  init_features: 32
  num_res: 5
training:
  epochs: 60
  batch_size: 65536
  pred_batch_size: 65536
  lr: 5.0e-5
  val_split: 0.1
  log_every: 1
  save_every: 5
  early_stop_patience: 0
  seed: 42
