experiment: exp_moe_inr_xyzt_to_velocity
exp_id: moeinr-ocean-velocity-sub
experiment_root: experiments
data:
  dataset_name: ocean
  split: train
  data_root: ./data
  x_path: ./data/raw/ocean/train/data_XYZT_sub.npy
  y_path: ./data/raw/ocean/train/data_V_time_sub.npy
  normalize: true
model:
  name: moe_inr
  in_features: 4
  out_features: 3
  num_experts: 7
  base_dim: 32
  encoder_num_res_blocks: 10
  encoder_first_omega_0: 30.0
  encoder_hidden_omega_0: 30.0
  policy_num_layers: 3
  policy_first_omega_0: 30.0
  policy_hidden_omega_0: 30.0
  expert_num_layers: 3
  expert_first_omega_0: 30.0
  expert_hidden_omega_0: 30.0
training:
  epochs: 60
  batch_size: 8192
  pred_batch_size: 8192
  lr: 5.0e-5
  val_split: 0.1
  log_every: 1
  save_every: 5
  early_stop_patience: 0
  seed: 42
