experiment: exp_moe_inr_cell_S_IntegrationPoints
exp_id: moeinr-cell-S-IntegrationPoints
experiment_root: experiments
data:
  dataset_name: sukong
  split: train
  data_root: ./data
  x_path: ./data/raw/sukong/train/source_cell_XYZT.npy
  y_path: ./data/raw/sukong/train/target_cell_S_IntegrationPoints.npy
  normalize: true
model:
  name: moe_inr
  in_features: 4
  out_features: 6
  num_experts: 7
  base_dim: 4
  encoder_first_omega_0: 30.0
  encoder_hidden_omega_0: 30.0
  policy_num_layers: 3
  policy_first_omega_0: 30.0
  policy_hidden_omega_0: 30.0
  expert_num_layers: 2
  expert_first_omega_0: 30.0
  expert_hidden_omega_0: 30.0
training:
  num_workers: 4
  epochs: 60
  batch_size: 16000
  pred_batch_size: 16000
  lr: 5.0e-5
  log_every: 1
  save_every: 10
  early_stop_patience: 0
  seed: 42
  resume_path: null
