experiment: exp_moe_inr_e_time
exp_id: moeinr-centroids-e_time
experiment_root: experiments
data:
  dataset_name: centroids
  split: train
  data_root: ./data
  x_path: ./data/raw/centroids/train/coords_xyzt.npy
  y_path: ./data/raw/centroids/train/targets_e_time.npy
  normalize: true
model:
  name: moe_inr
  in_features: 4
  out_features: 24
  num_experts: 7
  base_dim: 16
  encoder_num_res_blocks: 10
  encoder_first_omega_0: 30.0
  encoder_hidden_omega_0: 30.0
  policy_num_layers: 3
  policy_first_omega_0: 30.0
  policy_hidden_omega_0: 30.0
  expert_num_layers: 3
  expert_first_omega_0: 30.0
  expert_hidden_omega_0: 30.0
training:
  num_workers: 4
  epochs: 30
  batch_size: 65536
  pred_batch_size: 65536
  lr: 5.0e-5
  log_every: 1
  save_every: 5
  early_stop_patience: 0
  seed: 42
