experiment: exp9_basisExpert_centroids_multiview_xyzt
exp_id: basisExpert-centroids-multiview
experiment_root: experiments
data:
  dataset_name: centroids
  split: train
  data_root: ./data
  x_path: ./data/raw/centroids/train/coords_xyzt.npy
  attr_paths:
    target_s_centroid_time: ./data/raw/centroids/train/target_s_centroid_time.npy
    target_t_centroid_time: ./data/raw/centroids/train/target_e_centroid_time.npy
    targets_e_time: ./data/raw/centroids/train/targets_e_time.npy
    targets_s_time: ./data/raw/centroids/train/targets_s_time.npy
  normalize: true
model:
  name: basisExperts
  in_features: 4
  num_experts: 7
  base_dim: 16
  top_k: 2
  expert_use_positional_encoding: true
  expert_num_frequencies: 6
  expert_num_layers: 3
  gate_num_layers: 3
  decoder_num_layers: 3
  expert_first_omega_0: 30.0
  expert_hidden_omega_0: 30.0
  gate_first_omega_0: 30.0
  gate_hidden_omega_0: 30.0
  decoder_first_omega_0: 30.0
  decoder_hidden_omega_0: 30.0
training:
  num_workers: 4
  epochs: 60
  batch_size: 65536
  pred_batch_size: 65536
  lr: 5.0e-5
  log_every: 1
  save_every: 5
  early_stop_patience: 0
  seed: 42
  loss_type: mse
  lam_eq: 1.0e-2
  gam_div: 1.0e-3
